"""A setuptools based setup module.
See:
https://packaging.python.org/en/latest/distributing.html
https://github.com/pypa/sampleproject
Autogenerated by poetry-setup:
https://github.com/orsinium/poetry-setup
"""
# IMPORTANT: this file is autogenerated. Do not edit it manually.
# All changes will be lost after `poetry-setup` command execution.
# ----------------------------------------------------------------
# Always prefer setuptools over distutils
from setuptools import setup, find_packages
from os import path
# io.open is needed for projects that support Python 2.7
# It ensures open() defaults to text mode with universal newlines,
# and accepts an argument to specify the text encoding
# Python 3 only projects can skip this import
from io import open
here = path.abspath(path.dirname(__file__))
# Get the long description from the README file
with open(path.join(here, 'README.md'), encoding='utf-8') as f:
    long_description = f.read()
# Arguments marked as "Required" below must be included for upload to PyPI.
# Fields marked as "Optional" may be commented out.
setup(
    # https://packaging.python.org/specifications/core-metadata/#name
    name='poetry',  # Required
    # https://www.python.org/dev/peps/pep-0440/
    # https://packaging.python.org/en/latest/single_source_version.html
    version='0.11.4',  # Required
    # https://packaging.python.org/specifications/core-metadata/#summary
    description="Python dependency management and packaging made easy.",  # Required
    # https://packaging.python.org/specifications/core-metadata/#description-optional
    long_description=long_description,  # Optional
    # https://packaging.python.org/specifications/core-metadata/#description-content-type-optional
    long_description_content_type='text/markdown',  # Optional (see note above)
    url="https://poetry.eustace.io/",  # Optional
    author="Sébastien Eustace",  # Optional
    author_email="sebastien@eustace.io",  # Optional
    # For a list of valid classifiers, see https://pypi.org/classifiers/
    classifiers=[
        'License :: OSI Approved :: MIT License',
        'Programming Language :: Python :: 2',
        'Programming Language :: Python :: 2.7',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.4',
        'Programming Language :: Python :: 3.5',
        'Programming Language :: Python :: 3.6',
        'Programming Language :: Python :: 3.7',
        'Topic :: Software Development :: Build Tools',
        'Topic :: Software Development :: Libraries :: Python Modules'
    ],  # Optional
    keywords=' '.join(['packaging', 'dependency', 'poetry']),  # Optional
    packages=find_packages(),  # Required
    # https://packaging.python.org/en/latest/requirements.html
    install_requires=[
        'pyrsistent (>=0.14.2,<0.15.0)',
        'pathlib2 (>=2.3,<3.0); (python_version >= "2.7" and python_version < "2.8") or (python_version >= "3.4" and python_version < "3.5")',
        'jsonschema (>=2.6,<3.0)',
        'requests-toolbelt (>=0.8.0,<0.9.0)',
        'shellingham (>=1.1,<2.0)',
        'cleo (>=0.6.7,<0.7.0)',
        'pyparsing (>=2.2,<3.0)',
        'requests (>=2.18,<3.0)',
        'cachy (>=0.2,<0.3)',
        'virtualenv (>=16.0,<17.0); python_version >= "2.7" and python_version < "2.8"',
        'typing (>=3.6,<4.0); (python_version >= "2.7" and python_version < "2.8") or (python_version >= "3.4" and python_version < "3.5")',
        'tomlkit (>=0.4.0,<0.5.0)',
        'cachecontrol[filecache] (>=0.12.4,<0.13.0)',
        'html5lib (>=1.0,<2.0)',
        'pkginfo (>=1.4,<2.0)',
    ],  # Optional
    # https://setuptools.readthedocs.io/en/latest/setuptools.html#dependencies-that-aren-t-in-pypi
    dependency_links=[],  # Optional
    # https://stackoverflow.com/a/16576850
    include_package_data=True,
    entry_points={  # Optional
        'console_scripts': [
            'poetry=poetry.console:main',
        ],
    },
    # https://packaging.python.org/specifications/core-metadata/#project-url-multiple-use
    project_urls={  # Optional
        'homepage': 'https://poetry.eustace.io/',
    },
)
